### ISSUE TITLE
Variable consistency

### ISSUE THREAD

**Issue by coiller** [anggutierrez/foodstack#29]
https://github.com/anggutierrez/foodstack/blob/3a489214c87cbd40cec559ab7d74a6b0dc2d61e4/foodstack/Views/EntryCell.m#L30

Why would you use self.entry vs entry / _entry here?
Besides the naming looks ambiguous as well. Here is a NSDate. Why you named it createdAtOriginalString ?

**Comment by anggutierrez** [comment]
createdAtOriginalString is a reused variable from the Twitter client. It was originally had "originalString" because we created and formatted a new variable that we would use in place of the "original string", hence the name. 

I decided to cut out all the extra code for this project and simplified the code, but the original variable names stayed. I have changed the variable name to reflect this

As for "self.entry", it was what was originally taught to us in Codepath. I can see how this would be confusing, so I have switched that method to just read as [entry createdAt]

Completed
